export default {
  // BG1
  bg1_background: {
    type: 'sprite',
    src: new URL('../../assets/sprites/Backgrounds/BG1/background.png', import.meta.url).href,
    preload: true,
  },
  bg1_sky: {
    type: 'sprite',
    src: new URL('../../assets/sprites/Backgrounds/BG1/sky.png', import.meta.url).href,
    preload: true,
  },
  bg1_styling1: {
    type: 'sprite',
    src: new URL('../../assets/sprites/Backgrounds/BG1/backgroundstyling1.png', import.meta.url).href,
    preload: true,
  },
  bg1_styling2: {
    type: 'sprite',
    src: new URL('../../assets/sprites/Backgrounds/BG1/backgroundstyling2.png', import.meta.url).href,
    preload: true,
  },
  bg1_floor: {
    type: 'sprite',
    src: new URL('../../assets/sprites/Backgrounds/BG1/floor.png', import.meta.url).href,
    preload: true,
  },

  // BG2
  bg2_background: {
    type: 'sprite',
    src: new URL('../../assets/sprites/Backgrounds/BG2/background.png', import.meta.url).href,
    preload: true,
  },
  bg2_flags: {
    type: 'sprite',
    src: new URL('../../assets/sprites/Backgrounds/BG2/flags.png', import.meta.url).href,
    preload: true,
  },
  bg2_floor: {
    type: 'sprite',
    src: new URL('../../assets/sprites/Backgrounds/BG2/floor.png', import.meta.url).href,
    preload: true,
  },

  // BG3
  bg3_background: {
    type: 'sprite',
    src: new URL('../../assets/sprites/Backgrounds/BG3/background.png', import.meta.url).href,
    preload: true,
  },
  bg3_pillar: {
    type: 'sprite',
    src: new URL('../../assets/sprites/Backgrounds/BG3/pillar.png', import.meta.url).href,
    preload: true,
  },
  bg3_floor: {
    type: 'sprite',
    src: new URL('../../assets/sprites/Backgrounds/BG3/floor.png', import.meta.url).href,
    preload: true,
  },

  // BG4
  bg4_background: {
    type: 'sprite',
    src: new URL('../../assets/sprites/Backgrounds/BG4/background.png', import.meta.url).href,
    preload: true,
  },
  bg4_styling1: {
    type: 'sprite',
    src: new URL('../../assets/sprites/Backgrounds/BG4/backgroundstyling1.png', import.meta.url).href,
    preload: true,
  },
  bg4_flags: {
    type: 'sprite',
    src: new URL('../../assets/sprites/Backgrounds/BG4/flags.png', import.meta.url).href,
    preload: true,
  },
  bg4_floor: {
    type: 'sprite',
    src: new URL('../../assets/sprites/Backgrounds/BG4/floor.png', import.meta.url).href,
    preload: true,
  },

  // Player Idle frames
  player_idle_0: {
    type: 'sprite',
    src: new URL('../../assets/sprites/Characters/Player/Idle/skeleton-Idle_0.png', import.meta.url).href,
    preload: true,
  },
  player_idle_1: {
    type: 'sprite',
    src: new URL('../../assets/sprites/Characters/Player/Idle/skeleton-Idle_1.png', import.meta.url).href,
    preload: true,
  },
  player_idle_2: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Idle/skeleton-Idle_2.png', import.meta.url).href, preload: true },
  player_idle_3: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Idle/skeleton-Idle_3.png', import.meta.url).href, preload: true },
  player_idle_4: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Idle/skeleton-Idle_4.png', import.meta.url).href, preload: true },
  player_idle_5: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Idle/skeleton-Idle_5.png', import.meta.url).href, preload: true },
  player_idle_6: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Idle/skeleton-Idle_6.png', import.meta.url).href, preload: true },
  player_idle_7: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Idle/skeleton-Idle_7.png', import.meta.url).href, preload: true },
  player_idle_8: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Idle/skeleton-Idle_8.png', import.meta.url).href, preload: true },
  player_idle_9: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Idle/skeleton-Idle_9.png', import.meta.url).href, preload: true },

  // Player Walk frames - using individual PNGs for now
  player_walk_0: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Walk/skeleton-Walk_0.png', import.meta.url).href, preload: true },
  player_walk_1: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Walk/skeleton-Walk_1.png', import.meta.url).href, preload: true },
  player_walk_2: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Walk/skeleton-Walk_2.png', import.meta.url).href, preload: true },
  player_walk_3: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Walk/skeleton-Walk_3.png', import.meta.url).href, preload: true },
  player_walk_4: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Walk/skeleton-Walk_4.png', import.meta.url).href, preload: true },
  player_walk_5: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Walk/skeleton-Walk_5.png', import.meta.url).href, preload: true },
  player_walk_6: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Walk/skeleton-Walk_6.png', import.meta.url).href, preload: true },
  player_walk_7: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Walk/skeleton-Walk_7.png', import.meta.url).href, preload: true },
  player_walk_8: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Walk/skeleton-Walk_8.png', import.meta.url).href, preload: true },
  player_walk_9: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Walk/skeleton-Walk_9.png', import.meta.url).href, preload: true },
  player_walk_10: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Walk/skeleton-Walk_10.png', import.meta.url).href, preload: true },
  player_walk_11: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Walk/skeleton-Walk_11.png', import.meta.url).href, preload: true },
  player_walk_12: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Walk/skeleton-Walk_12.png', import.meta.url).href, preload: true },
  player_walk_13: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Walk/skeleton-Walk_13.png', import.meta.url).href, preload: true },
  player_walk_14: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Walk/skeleton-Walk_14.png', import.meta.url).href, preload: true },
  player_walk_15: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Walk/skeleton-Walk_15.png', import.meta.url).href, preload: true },
  player_walk_16: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Walk/skeleton-Walk_16.png', import.meta.url).href, preload: true },
  player_walk_17: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Walk/skeleton-Walk_17.png', import.meta.url).href, preload: true },

  // Player Combat Animations
  player_hit_0: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Hit/skeleton-Hit_0.png', import.meta.url).href, preload: true },
  player_hit_1: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Hit/skeleton-Hit_1.png', import.meta.url).href, preload: true },
  player_hit_2: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Hit/skeleton-Hit_2.png', import.meta.url).href, preload: true },
  player_hit_3: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Hit/skeleton-Hit_3.png', import.meta.url).href, preload: true },
  player_hit_4: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Hit/skeleton-Hit_4.png', import.meta.url).href, preload: true },
  player_hit_5: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Hit/skeleton-Hit_5.png', import.meta.url).href, preload: true },
  player_hit_6: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Hit/skeleton-Hit_6.png', import.meta.url).href, preload: true },
  player_hit_7: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Hit/skeleton-Hit_7.png', import.meta.url).href, preload: true },
  player_hit_8: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Hit/skeleton-Hit_8.png', import.meta.url).href, preload: true },
  player_hit_9: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Hit/skeleton-Hit_9.png', import.meta.url).href, preload: true },
  player_hit_10: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Hit/skeleton-Hit_10.png', import.meta.url).href, preload: true },
  player_hit_11: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Hit/skeleton-Hit_11.png', import.meta.url).href, preload: true },
  player_hit_12: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Hit/skeleton-Hit_12.png', import.meta.url).href, preload: true },
  player_hit_13: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Hit/skeleton-Hit_13.png', import.meta.url).href, preload: true },
  player_hit_14: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Hit/skeleton-Hit_14.png', import.meta.url).href, preload: true },
  player_hit_15: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Hit/skeleton-Hit_15.png', import.meta.url).href, preload: true },
  player_hit_16: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Hit/skeleton-Hit_16.png', import.meta.url).href, preload: true },
  player_hit_17: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Hit/skeleton-Hit_17.png', import.meta.url).href, preload: true },
  player_hit_18: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Hit/skeleton-Hit_18.png', import.meta.url).href, preload: true },
  player_hit_19: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Hit/skeleton-Hit_19.png', import.meta.url).href, preload: true },
  player_hit_20: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Hit/skeleton-Hit_20.png', import.meta.url).href, preload: true },
  player_hit_21: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Hit/skeleton-Hit_21.png', import.meta.url).href, preload: true },

  player_defense_0: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Defense/skeleton-Defense_0.png', import.meta.url).href, preload: true },
  player_defense_1: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Defense/skeleton-Defense_1.png', import.meta.url).href, preload: true },
  player_defense_2: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Defense/skeleton-Defense_2.png', import.meta.url).href, preload: true },
  player_defense_3: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Defense/skeleton-Defense_3.png', import.meta.url).href, preload: true },
  player_defense_4: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Defense/skeleton-Defense_4.png', import.meta.url).href, preload: true },
  player_defense_5: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Defense/skeleton-Defense_5.png', import.meta.url).href, preload: true },
  player_defense_6: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Defense/skeleton-Defense_6.png', import.meta.url).href, preload: true },
  player_defense_7: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Defense/skeleton-Defense_7.png', import.meta.url).href, preload: true },
  player_defense_8: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Defense/skeleton-Defense_8.png', import.meta.url).href, preload: true },
  player_defense_9: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Defense/skeleton-Defense_9.png', import.meta.url).href, preload: true },

  // Enemy1 Idle frames
  enemy1_idle_0: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Idle/skeleton-Idle_0.png', import.meta.url).href, preload: true },
  enemy1_idle_1: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Idle/skeleton-Idle_1.png', import.meta.url).href, preload: true },
  enemy1_idle_2: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Idle/skeleton-Idle_2.png', import.meta.url).href, preload: true },
  enemy1_idle_3: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Idle/skeleton-Idle_3.png', import.meta.url).href, preload: true },
  enemy1_idle_4: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Idle/skeleton-Idle_4.png', import.meta.url).href, preload: true },
  enemy1_idle_5: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Idle/skeleton-Idle_5.png', import.meta.url).href, preload: true },
  enemy1_idle_6: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Idle/skeleton-Idle_6.png', import.meta.url).href, preload: true },
  enemy1_idle_7: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Idle/skeleton-Idle_7.png', import.meta.url).href, preload: true },
  enemy1_idle_8: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Idle/skeleton-Idle_8.png', import.meta.url).href, preload: true },
  enemy1_idle_9: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Idle/skeleton-Idle_9.png', import.meta.url).href, preload: true },

  // Enemy2 Idle frames
  enemy2_idle_0: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy2/Idle/skeleton-Idle_0.png', import.meta.url).href, preload: true },
  enemy2_idle_1: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy2/Idle/skeleton-Idle_1.png', import.meta.url).href, preload: true },
  enemy2_idle_2: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy2/Idle/skeleton-Idle_2.png', import.meta.url).href, preload: true },
  enemy2_idle_3: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy2/Idle/skeleton-Idle_3.png', import.meta.url).href, preload: true },
  enemy2_idle_4: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy2/Idle/skeleton-Idle_4.png', import.meta.url).href, preload: true },
  enemy2_idle_5: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy2/Idle/skeleton-Idle_5.png', import.meta.url).href, preload: true },
  enemy2_idle_6: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy2/Idle/skeleton-Idle_6.png', import.meta.url).href, preload: true },
  enemy2_idle_7: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy2/Idle/skeleton-Idle_7.png', import.meta.url).href, preload: true },
  enemy2_idle_8: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy2/Idle/skeleton-Idle_8.png', import.meta.url).href, preload: true },
  enemy2_idle_9: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy2/Idle/skeleton-Idle_9.png', import.meta.url).href, preload: true },

  // Enemy3 Idle frames
  enemy3_idle_0: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy3/Idle/skeleton-Idle_0.png', import.meta.url).href, preload: true },
  enemy3_idle_1: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy3/Idle/skeleton-Idle_1.png', import.meta.url).href, preload: true },
  enemy3_idle_2: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy3/Idle/skeleton-Idle_2.png', import.meta.url).href, preload: true },
  enemy3_idle_3: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy3/Idle/skeleton-Idle_3.png', import.meta.url).href, preload: true },
  enemy3_idle_4: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy3/Idle/skeleton-Idle_4.png', import.meta.url).href, preload: true },
  enemy3_idle_5: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy3/Idle/skeleton-Idle_5.png', import.meta.url).href, preload: true },
  enemy3_idle_6: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy3/Idle/skeleton-Idle_6.png', import.meta.url).href, preload: true },
  enemy3_idle_7: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy3/Idle/skeleton-Idle_7.png', import.meta.url).href, preload: true },
  enemy3_idle_8: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy3/Idle/skeleton-Idle_8.png', import.meta.url).href, preload: true },
  enemy3_idle_9: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy3/Idle/skeleton-Idle_9.png', import.meta.url).href, preload: true },

  // Enemy1 Combat Animations
  enemy1_hit_0: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Hit/skeleton-Hit_0.png', import.meta.url).href, preload: true },
  enemy1_hit_1: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Hit/skeleton-Hit_1.png', import.meta.url).href, preload: true },
  enemy1_hit_2: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Hit/skeleton-Hit_2.png', import.meta.url).href, preload: true },
  enemy1_hit_3: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Hit/skeleton-Hit_3.png', import.meta.url).href, preload: true },
  enemy1_hit_4: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Hit/skeleton-Hit_4.png', import.meta.url).href, preload: true },
  enemy1_hit_5: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Hit/skeleton-Hit_5.png', import.meta.url).href, preload: true },
  enemy1_hit_6: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Hit/skeleton-Hit_6.png', import.meta.url).href, preload: true },
  enemy1_hit_7: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Hit/skeleton-Hit_7.png', import.meta.url).href, preload: true },
  enemy1_hit_8: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Hit/skeleton-Hit_8.png', import.meta.url).href, preload: true },
  enemy1_hit_9: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Hit/skeleton-Hit_9.png', import.meta.url).href, preload: true },
  enemy1_hit_10: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Hit/skeleton-Hit_10.png', import.meta.url).href, preload: true },
  enemy1_hit_11: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Hit/skeleton-Hit_11.png', import.meta.url).href, preload: true },
  enemy1_hit_12: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Hit/skeleton-Hit_12.png', import.meta.url).href, preload: true },
  enemy1_hit_13: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Hit/skeleton-Hit_13.png', import.meta.url).href, preload: true },
  enemy1_hit_14: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Hit/skeleton-Hit_14.png', import.meta.url).href, preload: true },
  enemy1_hit_15: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Hit/skeleton-Hit_15.png', import.meta.url).href, preload: true },
  enemy1_hit_16: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Hit/skeleton-Hit_16.png', import.meta.url).href, preload: true },
  enemy1_hit_17: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Hit/skeleton-Hit_17.png', import.meta.url).href, preload: true },
  enemy1_hit_18: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Hit/skeleton-Hit_18.png', import.meta.url).href, preload: true },
  enemy1_hit_19: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Hit/skeleton-Hit_19.png', import.meta.url).href, preload: true },
  enemy1_hit_20: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Hit/skeleton-Hit_20.png', import.meta.url).href, preload: true },
  enemy1_hit_21: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Hit/skeleton-Hit_21.png', import.meta.url).href, preload: true },

  // Player Death Animation (35 frames)
  player_death_0: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_0.png', import.meta.url).href, preload: true },
  player_death_1: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_1.png', import.meta.url).href, preload: true },
  player_death_2: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_2.png', import.meta.url).href, preload: true },
  player_death_3: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_3.png', import.meta.url).href, preload: true },
  player_death_4: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_4.png', import.meta.url).href, preload: true },
  player_death_5: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_5.png', import.meta.url).href, preload: true },
  player_death_6: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_6.png', import.meta.url).href, preload: true },
  player_death_7: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_7.png', import.meta.url).href, preload: true },
  player_death_8: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_8.png', import.meta.url).href, preload: true },
  player_death_9: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_9.png', import.meta.url).href, preload: true },
  player_death_10: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_10.png', import.meta.url).href, preload: true },
  player_death_11: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_11.png', import.meta.url).href, preload: true },
  player_death_12: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_12.png', import.meta.url).href, preload: true },
  player_death_13: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_13.png', import.meta.url).href, preload: true },
  player_death_14: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_14.png', import.meta.url).href, preload: true },
  player_death_15: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_15.png', import.meta.url).href, preload: true },
  player_death_16: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_16.png', import.meta.url).href, preload: true },
  player_death_17: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_17.png', import.meta.url).href, preload: true },
  player_death_18: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_18.png', import.meta.url).href, preload: true },
  player_death_19: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_19.png', import.meta.url).href, preload: true },
  player_death_20: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_20.png', import.meta.url).href, preload: true },
  player_death_21: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_21.png', import.meta.url).href, preload: true },
  player_death_22: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_22.png', import.meta.url).href, preload: true },
  player_death_23: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_23.png', import.meta.url).href, preload: true },
  player_death_24: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_24.png', import.meta.url).href, preload: true },
  player_death_25: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_25.png', import.meta.url).href, preload: true },
  player_death_26: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_26.png', import.meta.url).href, preload: true },
  player_death_27: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_27.png', import.meta.url).href, preload: true },
  player_death_28: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_28.png', import.meta.url).href, preload: true },
  player_death_29: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_29.png', import.meta.url).href, preload: true },
  player_death_30: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_30.png', import.meta.url).href, preload: true },
  player_death_31: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_31.png', import.meta.url).href, preload: true },
  player_death_32: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_32.png', import.meta.url).href, preload: true },
  player_death_33: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_33.png', import.meta.url).href, preload: true },
  player_death_34: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/Death/skeleton-Death_34.png', import.meta.url).href, preload: true },

  // Player Get Hit Animation (14 frames)
  player_gethit_0: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/GetHit/skeleton-GetHit_0.png', import.meta.url).href, preload: true },
  player_gethit_1: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/GetHit/skeleton-GetHit_1.png', import.meta.url).href, preload: true },
  player_gethit_2: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/GetHit/skeleton-GetHit_2.png', import.meta.url).href, preload: true },
  player_gethit_3: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/GetHit/skeleton-GetHit_3.png', import.meta.url).href, preload: true },
  player_gethit_4: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/GetHit/skeleton-GetHit_4.png', import.meta.url).href, preload: true },
  player_gethit_5: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/GetHit/skeleton-GetHit_5.png', import.meta.url).href, preload: true },
  player_gethit_6: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/GetHit/skeleton-GetHit_6.png', import.meta.url).href, preload: true },
  player_gethit_7: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/GetHit/skeleton-GetHit_7.png', import.meta.url).href, preload: true },
  player_gethit_8: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/GetHit/skeleton-GetHit_8.png', import.meta.url).href, preload: true },
  player_gethit_9: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/GetHit/skeleton-GetHit_9.png', import.meta.url).href, preload: true },
  player_gethit_10: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/GetHit/skeleton-GetHit_10.png', import.meta.url).href, preload: true },
  player_gethit_11: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/GetHit/skeleton-GetHit_11.png', import.meta.url).href, preload: true },
  player_gethit_12: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/GetHit/skeleton-GetHit_12.png', import.meta.url).href, preload: true },
  player_gethit_13: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Player/GetHit/skeleton-GetHit_13.png', import.meta.url).href, preload: true },

  // Enemy1 Death Animation (31 frames)
  enemy1_death_0: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_0.png', import.meta.url).href, preload: true },
  enemy1_death_1: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_1.png', import.meta.url).href, preload: true },
  enemy1_death_2: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_2.png', import.meta.url).href, preload: true },
  enemy1_death_3: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_3.png', import.meta.url).href, preload: true },
  enemy1_death_4: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_4.png', import.meta.url).href, preload: true },
  enemy1_death_5: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_5.png', import.meta.url).href, preload: true },
  enemy1_death_6: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_6.png', import.meta.url).href, preload: true },
  enemy1_death_7: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_7.png', import.meta.url).href, preload: true },
  enemy1_death_8: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_8.png', import.meta.url).href, preload: true },
  enemy1_death_9: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_9.png', import.meta.url).href, preload: true },
  enemy1_death_10: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_10.png', import.meta.url).href, preload: true },
  enemy1_death_11: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_11.png', import.meta.url).href, preload: true },
  enemy1_death_12: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_12.png', import.meta.url).href, preload: true },
  enemy1_death_13: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_13.png', import.meta.url).href, preload: true },
  enemy1_death_14: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_14.png', import.meta.url).href, preload: true },
  enemy1_death_15: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_15.png', import.meta.url).href, preload: true },
  enemy1_death_16: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_16.png', import.meta.url).href, preload: true },
  enemy1_death_17: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_17.png', import.meta.url).href, preload: true },
  enemy1_death_18: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_18.png', import.meta.url).href, preload: true },
  enemy1_death_19: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_19.png', import.meta.url).href, preload: true },
  enemy1_death_20: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_20.png', import.meta.url).href, preload: true },
  enemy1_death_21: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_21.png', import.meta.url).href, preload: true },
  enemy1_death_22: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_22.png', import.meta.url).href, preload: true },
  enemy1_death_23: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_23.png', import.meta.url).href, preload: true },
  enemy1_death_24: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_24.png', import.meta.url).href, preload: true },
  enemy1_death_25: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_25.png', import.meta.url).href, preload: true },
  enemy1_death_26: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_26.png', import.meta.url).href, preload: true },
  enemy1_death_27: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_27.png', import.meta.url).href, preload: true },
  enemy1_death_28: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_28.png', import.meta.url).href, preload: true },
  enemy1_death_29: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_29.png', import.meta.url).href, preload: true },
  enemy1_death_30: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/Death/skeleton-Death_30.png', import.meta.url).href, preload: true },

  // Enemy1 Get Hit Animation (14 frames)
  enemy1_gethit_0: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/GetHit/skeleton-GetHit_0.png', import.meta.url).href, preload: true },
  enemy1_gethit_1: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/GetHit/skeleton-GetHit_1.png', import.meta.url).href, preload: true },
  enemy1_gethit_2: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/GetHit/skeleton-GetHit_2.png', import.meta.url).href, preload: true },
  enemy1_gethit_3: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/GetHit/skeleton-GetHit_3.png', import.meta.url).href, preload: true },
  enemy1_gethit_4: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/GetHit/skeleton-GetHit_4.png', import.meta.url).href, preload: true },
  enemy1_gethit_5: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/GetHit/skeleton-GetHit_5.png', import.meta.url).href, preload: true },
  enemy1_gethit_6: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/GetHit/skeleton-GetHit_6.png', import.meta.url).href, preload: true },
  enemy1_gethit_7: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/GetHit/skeleton-GetHit_7.png', import.meta.url).href, preload: true },
  enemy1_gethit_8: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/GetHit/skeleton-GetHit_8.png', import.meta.url).href, preload: true },
  enemy1_gethit_9: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/GetHit/skeleton-GetHit_9.png', import.meta.url).href, preload: true },
  enemy1_gethit_10: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/GetHit/skeleton-GetHit_10.png', import.meta.url).href, preload: true },
  enemy1_gethit_11: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/GetHit/skeleton-GetHit_11.png', import.meta.url).href, preload: true },
  enemy1_gethit_12: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/GetHit/skeleton-GetHit_12.png', import.meta.url).href, preload: true },
  enemy1_gethit_13: { type: 'sprite', src: new URL('../../assets/sprites/Characters/Enemy1/GetHit/skeleton-GetHit_13.png', import.meta.url).href, preload: true },

  // Dust Particle Frames
  dust_particle_0: {
    type: 'sprite',
    src: new URL('../../assets/sprites/dust/tile000.png', import.meta.url).href,
    preload: true,
  },
  dust_particle_1: {
    type: 'sprite',
    src: new URL('../../assets/sprites/dust/tile001.png', import.meta.url).href,
    preload: true,
  },
  dust_particle_2: {
    type: 'sprite',
    src: new URL('../../assets/sprites/dust/tile002.png', import.meta.url).href,
    preload: true,
  },
  dust_particle_3: {
    type: 'sprite',
    src: new URL('../../assets/sprites/dust/tile003.png', import.meta.url).href,
    preload: true,
  },
  dust_particle_4: {
    type: 'sprite',
    src: new URL('../../assets/sprites/dust/tile004.png', import.meta.url).href,
    preload: true,
  },

  // Bitmap Font
  gladiators_font: {
    type: 'sprite',
    src: new URL('../../assets/fonts/font/Gladiators.png', import.meta.url).href,
    preload: true,
  },
  gladiators_fnt: {
    type: 'sprite',
    src: new URL('../../assets/fonts/font/Gladiators.fnt', import.meta.url).href,
    preload: true,
  },

} as const;
